In [52]:
from sklearn.model_selection import cross_val_score
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
import numpy as np

In [53]:
iris=load_iris()

In [54]:
l_scores=cross_val_score(LogisticRegression(),iris.data,iris.target)
l_scores

array([0.96078431, 0.92156863, 0.95833333])

In [55]:
np.average(l_scores)

0.9468954248366014

In [56]:
s_scores=cross_val_score(SVC(),iris.data,iris.target)
s_scores

array([0.98039216, 0.96078431, 0.97916667])

In [57]:
np.average(s_scores)

0.9734477124183006

In [58]:
d_scores=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
d_scores

array([0.98039216, 0.92156863, 0.97916667])

In [59]:
np.average(d_scores)

0.960375816993464

In [60]:
r_scores=cross_val_score(RandomForestClassifier(),iris.data,iris.target)
r_scores

array([0.98039216, 0.94117647, 0.97916667])

In [61]:
np.average(r_scores)

0.9669117647058822